name:          "Testing"
description:   "blah blah"
email:         theron.hitchman@uni.edu


url:           "http://dcernst.github.io"
baseurl:       "/PagesBootstrapTest"


markdown:      kramdown
highlighter:   pygments
