name: 'Dana C. Ernst'
description: 'Mathematics, Teaching, & Technology'
tagline: 'Mathematics, Teaching, & Technology'
url: 'http://dcernst.github.io'
baseurl: ''
paginate: 10

# Dependencies
markdown: kramdown
# redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# permalink: /:year/:month/:title/
relative_permalinks: false

# About/contact
author:
  name: "Dana C. Ernst"
  url: "https://twitter.com/danaernst"
  email: dana.ernst@nau.edu

twitter:
  username: danaernst

# GitHub
github:
  repo: github.com/dcernst/dcernst.github.io

# Feed Stuff
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
